services:
  syncing-server-js:
    image: standardnotes/syncing-server-js:${SYNCING_SERVER_JS_IMAGE_TAG}
    container_name: syncing-server-js-self-hosted
    depends_on:
      - db
      - cache
    entrypoint: [
      "./packages/syncing-server/wait-for.sh", "db", "3306",
      "./packages/syncing-server/wait-for.sh", "cache", "6379",
      "./packages/syncing-server/wait-for.sh", "localstack", "4566",
      "./packages/syncing-server/docker/entrypoint.sh", "start-web"
    ]
    env_file: .env
    environment:
      PORT: 3000
      FILE_UPLOAD_PATH: 'uploads/${FILE_UPLOAD_PATH}'
    volumes:
      - ./${FILE_UPLOAD_PATH}:/workspace/packages/syncing-server/uploads/${FILE_UPLOAD_PATH}
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  syncing-server-js-worker:
    image: standardnotes/syncing-server-js:${SYNCING_SERVER_JS_IMAGE_TAG}
    container_name: syncing-server-js-worker-self-hosted
    depends_on:
      - db
      - cache
      - syncing-server-js
    entrypoint: [
      "./packages/syncing-server/wait-for.sh", "db", "3306",
      "./packages/syncing-server/wait-for.sh", "cache", "6379",
      "./packages/syncing-server/wait-for.sh", "syncing-server-js", "3000",
      "./packages/syncing-server/docker/entrypoint.sh", "start-worker"
    ]
    env_file: .env
    environment:
      PORT: 3000
      FILE_UPLOAD_PATH: 'uploads/${FILE_UPLOAD_PATH}'
    volumes:
      - ./${FILE_UPLOAD_PATH}:/workspace/packages/syncing-server/uploads/${FILE_UPLOAD_PATH}
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  api-gateway:
    image: standardnotes/api-gateway:${API_GATEWAY_IMAGE_TAG}
    container_name: api-gateway-self-hosted
    depends_on:
      - auth
      - syncing-server-js
    env_file: docker/api-gateway.env
    ports:
      - ${EXPOSED_PORT}:3000
    environment:
      PORT: 3000
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
      REDIS_URL: '${REDIS_URL}'
      FILES_SERVER_URL: '${FILES_SERVER_URL}'
    entrypoint: [
      "./packages/api-gateway/wait-for.sh", "auth", "3000",
      "./packages/api-gateway/wait-for.sh", "syncing-server-js", "3000",
      "./packages/api-gateway/wait-for.sh", "files", "3000",
      "./packages/api-gateway/wait-for.sh", "revisions", "3000",
      "./packages/api-gateway/docker/entrypoint.sh", "start-web"
    ]
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  auth:
    image: standardnotes/auth:${AUTH_IMAGE_TAG}
    container_name: auth-self-hosted
    depends_on:
      - db
      - cache
      - syncing-server-js
    entrypoint: [
      "./packages/auth/wait-for.sh", "db", "3306",
      "./packages/auth/wait-for.sh", "cache", "6379",
      "./packages/auth/wait-for.sh", "localstack", "4566",
      "./packages/auth/wait-for.sh", "syncing-server-js", "3000",
      "./packages/auth/docker/entrypoint.sh", "start-web"
    ]
    env_file: docker/auth.env
    environment:
      PORT: 3000
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${DB_MIGRATIONS_PATH}'
      REDIS_URL: '${REDIS_URL}'
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
      VALET_TOKEN_SECRET: '${VALET_TOKEN_SECRET}'
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  auth-worker:
    image: standardnotes/auth:${AUTH_IMAGE_TAG}
    container_name: auth-worker-self-hosted
    depends_on:
      - db
      - cache
      - auth
    entrypoint: [
      "./packages/auth/wait-for.sh", "db", "3306",
      "./packages/auth/wait-for.sh", "cache", "6379",
      "./packages/auth/wait-for.sh", "auth", "3000",
      "./packages/auth/docker/entrypoint.sh", "start-worker"
    ]
    env_file: docker/auth.env
    environment:
      PORT: 3000
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${DB_MIGRATIONS_PATH}'
      REDIS_URL: '${REDIS_URL}'
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
      VALET_TOKEN_SECRET: '${VALET_TOKEN_SECRET}'
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  files:
    image: standardnotes/files:${FILES_IMAGE_TAG}
    container_name: files-self-hosted
    entrypoint: [
      "./packages/files/wait-for.sh", "db", "3306",
      "./packages/files/wait-for.sh", "cache", "6379",
      "./packages/files/wait-for.sh", "localstack", "4566",
      "./packages/files/docker/entrypoint.sh", "start-web"
    ]
    ports:
      - ${EXPOSED_FILES_PORT}:3000
    env_file: docker/files.env
    environment:
      FILE_UPLOAD_PATH: 'uploads/${FILE_UPLOAD_PATH}'
      VALET_TOKEN_SECRET: '${VALET_TOKEN_SECRET}'
    volumes:
      - ./${FILE_UPLOAD_PATH}:/workspace/packages/files/uploads/${FILE_UPLOAD_PATH}
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  files-worker:
    image: standardnotes/files:${FILES_IMAGE_TAG}
    container_name: files-worker-self-hosted
    depends_on:
      - files
    entrypoint: [
      "./packages/files/wait-for.sh", "files", "3000",
      "./packages/files/wait-for.sh", "localstack", "4566",
      "./packages/files/docker/entrypoint.sh", "start-worker"
    ]
    env_file: docker/files.env
    environment:
      FILE_UPLOAD_PATH: 'uploads/${FILE_UPLOAD_PATH}'
      VALET_TOKEN_SECRET: '${VALET_TOKEN_SECRET}'
    volumes:
      - ./${FILE_UPLOAD_PATH}:/workspace/packages/files/uploads/${FILE_UPLOAD_PATH}
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  revisions:
    image: standardnotes/revisions:${REVISIONS_IMAGE_TAG}
    container_name: revisions-self-hosted
    entrypoint: [
      "./packages/revisions/wait-for.sh", "syncing-server-js", "3000",
      "./packages/revisions/wait-for.sh", "revisions-db", "3306",
      "./packages/revisions/wait-for.sh", "localstack", "4566",
      "./packages/revisions/docker/entrypoint.sh", "start-web"
    ]
    env_file: docker/revisions.env
    environment:
      PORT: 3000
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
      DB_HOST: '${REVISIONS_DB_HOST}'
      DB_PORT: '${REVISIONS_DB_PORT}'
      DB_DATABASE: '${REVISIONS_DB_DATABASE}'
      DB_USERNAME: '${REVISIONS_DB_USERNAME}'
      DB_PASSWORD: '${REVISIONS_DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${REVISIONS_DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${REVISIONS_DB_MIGRATIONS_PATH}'
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  revisions-worker:
    image: standardnotes/revisions:${REVISIONS_IMAGE_TAG}
    container_name: revisions-worker-self-hosted
    entrypoint: [
      "./packages/revisions/wait-for.sh", "revisions", "3000",
      "./packages/revisions/docker/entrypoint.sh", "start-worker"
    ]
    env_file: docker/revisions.env
    environment:
      PORT: 3000
      AUTH_JWT_SECRET: '${AUTH_JWT_SECRET}'
      DB_HOST: '${REVISIONS_DB_HOST}'
      DB_PORT: '${REVISIONS_DB_PORT}'
      DB_DATABASE: '${REVISIONS_DB_DATABASE}'
      DB_USERNAME: '${REVISIONS_DB_USERNAME}'
      DB_PASSWORD: '${REVISIONS_DB_PASSWORD}'
      DB_DEBUG_LEVEL: '${REVISIONS_DB_DEBUG_LEVEL}'
      DB_MIGRATIONS_PATH: '${REVISIONS_DB_MIGRATIONS_PATH}'
      FILE_UPLOAD_PATH: 'uploads/${FILE_UPLOAD_PATH}'
    volumes:
      - ./${FILE_UPLOAD_PATH}:/workspace/packages/revisions/uploads/${FILE_UPLOAD_PATH}
    restart: on-failure
    networks:
      - standardnotes_self_hosted

  db:
    image: mysql:5.6
    container_name: db-self-hosted
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    expose:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted

  revisions-db:
    image: mysql:8
    container_name: revisions-db-self-hosted
    environment:
      MYSQL_DATABASE: '${REVISIONS_DB_DATABASE}'
      MYSQL_USER: '${REVISIONS_DB_USERNAME}'
      MYSQL_PASSWORD: '${REVISIONS_DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${REVISIONS_DB_PASSWORD}'
    expose:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data/revisions-db:/var/lib/mysql
    networks:
      - standardnotes_self_hosted

  cache:
    image: redis:6.0-alpine
    container_name: cache-self-hosted
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - standardnotes_self_hosted

  localstack:
    image: localstack/localstack
    expose:
      - 4566
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./docker/localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
