name: Testing With Stable Client And Server

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      snjs:
        image: standardnotes/snjs
        ports:
        - 9001:9001
      mock-event-publisher:
        image: standardnotes/mock-event-publisher
        ports:
        - 3124:3000
        env:
          LOG_LEVEL: debug
          NODE_ENV: production
          VERSION: snjs-test
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:payments-local-topic
          SNS_ENDPOINT: http://localstack:4566
          SNS_DISABLE_SSL: true
          SNS_SECRET_ACCESS_KEY: x
          SNS_ACCESS_KEY_ID: x
          SNS_AWS_REGION: us-east-1
          NEW_RELIC_ENABLED: false
        options: >-
          --name "mock-event-publisher"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout On Previous Commit
        run: git checkout HEAD~1
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Headless Chrome
        run: yarn global add mocha-headless-chrome
      - name: Initialize Default Configuration
        run: |
          ./server.sh setup
          ./server.sh generate-keys
      - name: Setup shorter session TTLs for testing
        run: |
          sed -i "s/ACCESS_TOKEN_AGE=.*/ACCESS_TOKEN_AGE=4/g" docker/auth.env
          sed -i "s/REFRESH_TOKEN_AGE=.*/REFRESH_TOKEN_AGE=10/g" docker/auth.env
          sed -i "s/EPHEMERAL_SESSION_AGE=.*/EPHEMERAL_SESSION_AGE=300/g" docker/auth.env
      - name: Setup shorter revisions creating frequency
        run: |
          sed -i "s/REVISIONS_FREQUENCY=.*/REVISIONS_FREQUENCY=5/g" .env
      - name: Setup debug log levels
        run: |
          sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/g" docker/auth.env
          sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/g" docker/api-gateway.env
          sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/g" docker/files.env
          sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/g" docker/revisions.env
          sed -i "s/LOG_LEVEL=.*/LOG_LEVEL=debug/g" .env
      - name: Start Stable Server
        run: ./server.sh start
        env:
          EXPOSED_PORT: 3123
      - name: Wait for Startup
        run: ./server.sh wait-for-startup
      - name: Checkout On Latest Commit
        run: git switch -
      - name: Initialize Default Configuration on Latest Commit
        run: |
          ./server.sh restore-config-defaults
          ./server.sh generate-keys
      - name: Start Updating Server
        run: ./server.sh update
        env:
          EXPOSED_PORT: 3123
      - name: Wait for Startup
        run: ./server.sh wait-for-startup
      - name: Connect external containers to self-hosted network
        run: docker network connect --alias mock-event-publisher standardnotes_self_hosted mock-event-publisher
      - name: Test
        run: ./server.sh test
